---

- name: create groups
  group:
    name: '{{ item.name }}'
    system: '{{ item.system | default(omit) }}'
    gid: '{{ item.gid | default(omit) }}'
    state: '{{ item.state | default("present") }}'
  with_items: '{{ groups_group }}'
  when: item.name is defined and item.name
